eventos/urls.py
from django.urls import path

# from .views import index, contato, evento
# from polls.views import EventosView
from .views import evento

urlpatterns = [
    # path('', index, name='index'),
    path('', evento, name='index.html'),
    # path('contato/', contato, name='contato'),
    # path('eventos/', evento, name='eventos'),
    # path('', EventosView.as_view(), name='index.html'),
]

polls/urls.py
from django.urls import path
from galeria.views import foto
# from .views import ContatoView, VideosView, EventosView, Dia1View
from .views import ContatoView, VideosView


from .import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index.html'),
    path('<int:pk>/', views.DetailView.as_view(), name='details'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('videos/', VideosView.as_view(), name='videos.html'),
    path('contato/', ContatoView.as_view(), name='contato.html'),
    path('foto/', foto, name='foto.html'),
]

societyaabb/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('polls.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('blog/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('eventos/', include('eventos.urls')),
    path('galeria/', include('galeria.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventos/models.py
from django.db import models

from django.utils import timezone

# SIGNALS
from django.db.models import signals
from django.template.defaultfilters import slugify


class Base2(models.Model):
    criado = models.DateField('Data de Criação', auto_now_add=True),
    modificado = models.DateField('Data de Atualização', auto_now=True),
    ativo = models.BooleanField('Ativo?', default=True),
    titulo = models.CharField(max_length=200)
    data_criacao = models.DateTimeField(default=timezone.now)
    data_publicacao = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.titulo

    class Meta:
        abstract = True


class Evento(Base2):
    titulo = models.CharField('Título', max_length=100)
    autor = models.CharField('Autor', max_length=100)
    lugar = models.CharField('local', max_length=50)
    slug = models.SlugField('Slug', max_length=100, blank=True, editable=False)

    def publicar(self):
        self.criado = timezone.now()
        self.save()

    def __std__(self):
        return self.titulo


def evento_pre_save(signal, instance, sender, **kwargs):
    instance.slug = slugify(instance.titulo)


signals.pre_save.connect(evento_pre_save, sender=Evento)

polls/models.py
from datetime import timedelta

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'

    was_published_recently.boolean = True

    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

eventos/forms.py
from django import forms
# from django.core.mail.message import EmailMessage
from .models import Evento

'''
class ContatoForm(forms.Form):
    nome = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='Email', max_length=100)
    assunto = forms.CharField(label='Assunto', max_length=120)
    mensagem = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_mail(self):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        assunto = self.cleaned_data['assunto']
        mensagem = self.cleaned_data['mensagem']

        conteudo = f'Nome: {nome}\nEmail: {email}\nAssunto: {assunto}\nMensagem: {mensagem}'

        mail = EmailMessage(
            subject='Email enviado pelo sistema django2',
            body=conteudo,
            from_email='contato@seudominio.com.br',
            to=['contato@seudominio.com', ],
            headers={'Reply-To': email}
        )
        mail.send()
'''


class EventoModelForm(forms.ModelForm):
    class Meta:
        model = Evento
        fields = ['titulo', 'autor', 'lugar']

eventos/views.py
from django.shortcuts import render

# from django.shortcuts import redirect

# from .forms import EventoModelForm

# from .forms import ContatoForm, EventoModelForm

from .models import Evento
from django.core.paginator import Paginator

"""
def evento(request):
    context = {
        'eventos': Evento.objects.all().order_by('data_publicacao')
    }

    return render(request, 'eventos/index.html', context)
"""


def evento(request):
    eventos = Evento.objects.all().order_by("data_publicacao")
    paginator = Paginator(eventos, 5)

    page = request.GET.get('p')
    eventos = paginator.get_page(page)

    return render(request, 'eventos/index.html', {'eventos': eventos})

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from .models import Question, Choice
from django.views import generic
from django.views.generic import TemplateView
from django.utils import timezone
# from django.contrib import messages
from django.shortcuts import render


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/details.html', {
            'question': question,
            'error_message': "Você não selecionou uma escolha.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class VideosView(TemplateView):
    template_name = 'polls/videos.html'


class EventosView(TemplateView):
    template_name = 'polls/index.html'


class ContatoView(TemplateView):
    template_name = 'polls/contato.html'

# class Dia1View(TemplateView):
# template_name = 'polls/dia1.html'

polls/templates/polls/contato.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
      <title>Mysite - Contato</title>
      {% include 'parciais/_head.html' %}
  </head>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #00509D">
  <a class="navbar-brand text-white"><img src="{% static 'polls/images/final20.png' %}" alt="" href="/">da AABB</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link text-white" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/videos">Vídeos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/eventos">Eventos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/galeria">Galeria <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/blog">Blog</a> <span class="sr-only">(current)</span>
      </li>
      <li class="nav-item active">
        <a class="nav-link text-white" href="#">Contato</a> <span class="sr-only">(current)</span>
      </li>
    </ul>
  </div>
</nav>
  <body style="background-color: #f9f9f9;">
            <div class="row pt-5">
                  <div class="col-xl"></div>
                  <div class="col-xl-8 text-center">
                      <p><h5>Contato para desenvolvimento:</h5>
                          <img class="rounded-circle" src="{% static 'polls/images/perfil2.jpg' %}"
                               alt="Imagem responsiva">
                          <center>
                          <p class="card-text"><b><i>Alves</i></b></p>
                          </center>

                      <ul class="list-group list-group-flush">
                          <li class="list-group-item"><b><i><i class="fa fa-home" aria-hidden="true"></i>
                              Rua dos Lírios nº 09 - Primavera - São Raimundo das Mangabeiras - MA - CEP: 65.840-000</i>
                          </b></li>
                          <li class="list-group-item"><b><i><i class="fa fa-envelope-o" aria-hidden="true"></i>
                              jweseles_al@hotmail.com</i></b></li>
                          <li class="list-group-item"><b><i><i class="fa fa-whatsapp" aria-hidden="true"></i>
                              (99)98474-7008</i></b></li>
                      </ul>

                  </div>
              <div class="col-xl"></div>
            </div>
            <br><br><br><br>
        <footer>
            {% include 'parciais/_footer.html' %}
        </footer>
            <script src="{% static 'assets/js/jquery-3.5.1.min.js' %}"></script>
            <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
            <script src="{% static 'assets/js/popper.min.js' %}"></script>
  </body>
</html>

polls/templates/polls/details.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
    <title>Mysite - Detalhe</title>
      {% include 'parciais/_head.html' %}
  </head>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #00509D">
  <a class="navbar-brand text-white"><img src="{% static 'polls/images/final20.png' %}" alt="" href="/">da AABB</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link text-white" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>
  <body style="background-color: #f9f9f9;">
      <div class="container">
          <br>
              <center><p><h5>Os atletas mais habilidosos de São Raimundo das Mangabeiras - MA</h5></center>
              <div class="row">
                  <div class="col-3"></div>
                  <div class="col-12 col-md-6">
                      <ul>
                          <br>
                          <p><b>{{ question.question_text }}</b></p>
                          {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                          <form action="{% url 'polls:vote' question.id %}" method="post">
                              {% csrf_token %}
                              {% for choice in question.choice_set.all %}
                              <input type="radio" name="choice" id="choice{{ forloop.counter }}"
                                     value="{{ choice.id }}">
                              <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                              {% endfor %}
                              <button type="submit" class="btn btn-outline text-white"
                                      style="background-color: #FDC500">Votar</button>
                          </form>
                      </ul>
                      <div class="card-body">
                          <p class="card-text"></p>
                      </div>
                  </div>
              </div>
      </div>
      <br><br><br><br><br>
      <footer>
          {% include 'parciais/_footer.html' %}
      </footer>
            <script src="{% static 'assets/js/jquery-3.5.1.min.js' %}"></script>
            <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
            <script src="{% static 'assets/js/popper.min.js' %}"></script>
  </body>
</html>

polls/templates/polls/eventos.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
    <title>Mysite - Eventos</title>
      {% include 'parciais/_head.html' %}
  </head>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #00509D">
  <a class="navbar-brand"><img src="{% static 'polls/images/final20.png' %}" alt="" href="/">da AABB</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link text-white" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/videos">Vídeos<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link text-white" href="#">Eventos<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/galeria">Galeria<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/blog">Blog<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/contato">Contato<span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>
  <body style="background-color: #f9f9f9;">
        <div class="container shadow-lg p-3 mb-5 bg-white rounded">
              <center><p><h5>Programação dos Eventos agendados:</h5></center>
              <div class="row">
                 <div class="col-12 col-md-3"></div>
                      <div class="col-12 col-md-6">
                            <div class="card mt-1 shadow-lg p-3 mb-5 bg-white rounded">
                              <table class="table table-striped">
                                  <thead>
                                        <tr>
                                          {% if reserva %}
                                            <table class="table">
                                                  <thead>
                                                    <tr>
                                                      <th scope="col">#</th>
                                                      <th scope="col">Título</th>
                                                      <th scope="col">Nome</th>
                                                      <th scope="col">Data</th>
                                                    </tr>
                                                  </thead>
                                                  <tbody>
                                                    {% for evento in reserva  %}
                                                        <tr>
                                                            <td scope="row">{{ evento.id }}</td>
                                                            <td scope="row"><a href="#modal{{evento.id}}" data-toggle="modal">{{ evento.titulo }}</a></td>
                                                            <td scope="row">{{ evento.autor }}</td>
                                                            <td scope="row">{{ evento.data_criacao }}</td>
                                                        </tr>
                                                                           <!-- Button trigger modal -->

                                                        <!-- Modal -->
                                                        <div class="modal fade" id="modal{{evento.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                          <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                              <div class="modal-header">

                                                                  <h5 class="modal-title" id="exampleModalLabel">{{ evento.titulo }}</h5>

                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                  <span aria-hidden="true">&times;</span>
                                                                </button>
                                                              </div>
                                                              <div class="modal-body">
                                                                  <center>
                                                                   <img src="{{ evento.imagem.url }}" style="max-width:300px;
                                                                   height:auto;" class="img-fluid" alt="{{foto.titulo}}"/>
                                                                  </center>
                                                              </div>
                                                              <div class="modal-footer">
                                                                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                                                              </div>
                                                            </div>
                                                          </div>
                                                        </div>
                                                    {% endfor %}
                                                  </tbody>
                                            </table>
                                            {% else %}
                                            <center>
                                            <h5>Ainda não existem eventos cadastrados. :(</h5>
                                                </center>
                                          {% endif %}
                                        </tr>
                                  </thead>
                              </table>
                            </div>
                      </div>
                 </div>
              </div>
        </div>
          <footer>
              {% include 'parciais/_footer.html' %}
          </footer>
          <script src="{% static 'assets/js/jquery-3.5.1.min.js' %}"></script>
          <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
          <script src="{% static 'assets/js/popper.min.js' %}"></script>
  </body>
</html>

polls/templates/polls/index.html
{% extends 'base2.html' %}
{% load static %}

{%block conteudo%}
<div class="container">
    <center><p><h5>Os atletas mais habilidosos de São Raimundo das Mangabeiras - MA</h5></center>
    <br>
    <div class="row">
        <div class="col-12 col-md-6">
            <p class="card-text"><center>Seleção BB</center>
            <br>
            <img src="{% static 'polls/images/timebb.jpg' %}" class="img-fluid" alt="Imagem responsiva"
                 width="840" height="390">
        </div>
        <div class="col-12 col-md-6">
            <p class="card-text"><center>Amistoso: BB 4 x 4 IFMA - 14/12/2020</center>
            <br>
            <img src="{% static 'polls/images/bbxifma.jpg' %}" class="img-fluid" alt="Imagem responsiva"
                 width="840" height="390">
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-12 col-md-6">
            <p class="card-text"><center>Imagem Racha 1</center>
            <br>
            <img src="{% static 'polls/images/pagina1.jpg' %}" class="img-fluid" alt="Imagem responsiva"
                 width="840" height="390">

        </div>
        <div class="col-12 col-md-6">
            <p class="card-text"><center>Imagem Racha 2</center>
            <br>
            <img src="{% static 'polls/images/pagina2.jpg' %}" class="img-fluid" alt="Imagem responsiva"
                 width="840" height="390">

        </div>
    </div>
    <br><br>
    <div class="row">
        <div class="col-12 col-md-3"></div>
        <div class="col-12 col-md-6 text-dark">
            <center><h5>Participe da enquete abaixo:</h5></center>
            <ul>
                <center>
                {% if latest_question_list %}
                {% for question in latest_question_list %}
                     <a href="{% url 'polls:details' question.id %}"><i class="fa fa-list-ol" aria-hidden="true">
                         </i> {{ question.question_text }}</a>
                {% endfor %}
                {% else %}
                <p>No polls are available.</p>
                {% endif %}
                    </center>
            </ul>
        </div>
    </div>
</div>
{%endblock%}

polls/templates/polls/results.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
    <title>Mysite - Resultado</title>
      {% include 'parciais/_head.html' %}
  </head>
   <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #00509D">
  <a class="navbar-brand text-white"><img src="{% static 'polls/images/final20.png' %}" alt="" href="/">da AABB</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link text-white" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>
  <body style="background-color: #f9f9f9;">
  <div class="container">
      <br>
          <center>
	      <p><h5>Os atletas mais habilidosos de São Raimundo das Mangabeiras - MA</h5>
          </center>

	      <div class="row">
	          <div class="col-12 col-md-6">
                  <p class="card-text"><center>Imagem 1 - Jogadores</center>
                  <br>
	                    <img class="card-img-top" src="{% static 'polls/images/ajustada1.jpg' %}" alt="Imagem responsiva">
              </div>
              <div class="col-12 col-md-6">
                  <p class="card-text"><center>Imagem 2 - Jogadores</center>
                  <br>
                        <img class="card-img-top" src="{% static 'polls/images/ajustada2.jpg' %}" alt="Imagem responsiva">
              </div>
              <div class="col-3"></div>
              <div class="col-12 col-md-6 mt-3">
                        <ul>
                                <br>
                                <p><b>{{ question.question_text }}</b></p>
                                {% for choice in question.choice_set.all %}
                                <p><i><i class="fa fa-list"></i> {{ choice.choice_text }}</i>
                                    <i class="fa fa-arrow-right"></i>
                                    {{ choice.votes }} vote{{ choice.votes|pluralize }}</p>
                                {% endfor %}
                                <a href="{% url 'polls:details' question.id %}"><button type="button" class="btn btn-outline
                            text-white" style="background-color: #FDC500">Quer votar novamente?</button></a>
                        </ul>
                        <div class="card-body">
                            <p class="card-text"></p>
                        </div>
              </div>
          </div>
  </div>
  <footer>
      {% include 'parciais/_footer.html' %}
  </footer>
        <script src="{% static 'assets/js/jquery-3.5.1.min.js' %}"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'assets/js/popper.min.js' %}"></script>
  </body>
</html>

polls/templates/polls/videos.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
    <title>Mysite - Vídeos</title>
      {% include 'parciais/_head.html' %}
  </head>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #00509D">
  <a class="navbar-brand text-white"><img src="{% static 'polls/images/final20.png' %}" alt="" href="/">da AABB</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link text-white" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link text-white" href="#">Vídeos <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/eventos">Eventos <span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item">
        <a class="nav-link text-white" href="/galeria">Galeria<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/blog">Blog<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="/contato">Contato <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>
  <body style="background-color: #f9f9f9;">
  <br>
  <div class="container">
          <center><p><h5>Os atletas mais habilidosos de São Raimundo das Mangabeiras - MA</h5></center>
      <br>
	      <div class="row">
	          <div class="col-12 col-md-6">
                  <p class="card-text"><center>Melhores momentos - 11/12/2020</center>
                  <br>
	                    <video controls autoplay width="100%" height="auto">
                            <source src="{% static 'polls/video/completo.mp4' %}">
                            <source src="{% static 'polls/video/completo.webm' %}">
                            <source src="{% static 'polls/video/completo.ogv' %}">
	                        <div class="card-body">
                                <br>
                            </div>
                        </video>
              </div>
              <div class="col-12 col-md-6">
                  <p class="card-text"><center>Ramison - Gol - 1</center>
                  <br>
                        <video controls autoplay width="100%" height="auto">
                            <source src="{% static 'polls/video/ramison01.mp4' %}">
                            <source src="{% static 'polls/video/ramison01.webm' %}">
                            <source src="{% static 'polls/video/ramison01.ogv' %}">
                            <div class="card-body">
                                <br>
                            </div>
                        </video>
              </div>
              <div class="col-12 col-md-6">
                  <p class="card-text"><center>Geovane - Gol - 2</center>
                  <br>
                        <video controls autoplay width="100%" height="auto">
                            <source src="{% static 'polls/video/geovane03.mp4' %}">
                            <source src="{% static 'polls/video/geovane03.webm' %}">
                            <source src="{% static 'polls/video/geovane03.ogv' %}">
                            <div class="card-body">
                                <br>
                            </div>
                        </video>
              </div>
              <div class="col-12 col-md-6">
                  <p class="card-text"><center>Homenagem ao 2º melhor de todos os tempos:</center>
                  <br>
                        <video controls autoplay width="100%" height="303">
                            <source src="{% static 'polls/video/maradona.mp4' %}">
                            <source src="{% static 'polls/video/maradona.webm' %}">
                            <source src="{% static 'polls/video/maradona.ogv' %}">
                            <div class="card-body">
                                <br>
                            </div>
                        </video>
              </div>
          </div>
  </div>
  <br><br>
  <footer>
      {% include 'parciais/_footer.html' %}
  </footer>
        <script src="{% static 'assets/js/jquery-3.5.1.min.js' %}"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'assets/js/popper.min.js' %}"></script>
  </body>
</html>